name: Publish
on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"
env:
  pkg_name: tachidesk-sorayomi
jobs:
  create-build:
    name: Create ${{ matrix.target }} build
    runs-on: ${{ matrix.os }}
    # softprops/action-gh-release needs this permission
    permissions:
      contents: write

    strategy:
      # Disable fail-fast as we want results from all even if one fails.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: android
            build_path: build/app/outputs/flutter-apk

    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Install Android dependencies
      - name: Install Android dependencies
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17.x"

      # Recreating the project
      - run: flutter doctor -v
      - uses: actions/checkout@v3
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: dart run build_runner build --delete-conflicting-outputs

      # Configure Keystore for Android
      - name: Configure Keystore for Android
        working-directory: android
        run: |
          echo "${{ secrets.PLAY_STORE_UPLOAD_KEY }}" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> key.properties
          echo "storePassword=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> key.properties

      # Build the project for Android
      - run: |
          flutter build apk --release
          flutter build apk --split-per-abi --release

      # Android packaging
      - name: Rename build for Android
        working-directory: ${{ matrix.build_path }}
        run: |
          mv app-release.apk "$GITHUB_WORKSPACE/${{ env.pkg_name }}-${{ github.ref_name }}-${{ matrix.target }}-all.apk"
          mv app-arm64-v8a-release.apk "$GITHUB_WORKSPACE/${{ env.pkg_name }}-${{ github.ref_name }}-${{ matrix.target }}-arm64-v8a.apk"
          mv app-armeabi-v7a-release.apk "$GITHUB_WORKSPACE/${{ env.pkg_name }}-${{ github.ref_name }}-${{ matrix.target }}-armeabi-v7a.apk"
          mv app-x86_64-release.apk "$GITHUB_WORKSPACE/${{ env.pkg_name }}-${{ github.ref_name }}-${{ matrix.target }}-x86_64.apk"

      - name: Add packaged build to release draft
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: ${{ env.pkg_name }}*
          token: ${{ secrets.DEPLOY_TOKEN }}
